### PR TITLE
Get element by atomic number

### PR DESCRIPTION
**Pull request by nathanhleung**
It would be great if one could get elements by atomic number!

### CODE REVIEW

**Comment by andrejewski** [comment]
Generally you don't want to have an object with keys which are numbers. A better way is
```js
var byAtomicNumber = data.sort(function(a,b) {return a.atomicNumber-b.atomicNumber;});
```

Then someone could do
```js
function getElementByNumber(num) {
  return byAtomicNumber[num-1];
}
```

The `pt.elements` and `pt.symbols` objects have string keys, but numeric-based access is best implemented as an array, which is a 3-liner at worst. I will not accept this pull, but I thank you for contributing. If you find a problem with the dataset or want to add something to the util module, please don't hesitate to pull/issue or contact me.

**Comment by nathanhleung** [comment]
Thanks for your quick response and explanation!

**Comment by nathanhleung** [comment]
Just wondering, would you be open to a pull for a _method_ that allowed one to get elements by atomic number (rather than a property)? For example `pt.byAtomicNum(6)`.

While it is trivial to implement outside of the package (as you mention above), my personal preference would be to have a built-in method akin to the elements by name and symbol functionality which is already implemented - there's extra mental overhead in converting between atomic numbers and array indexes and back which I'd just rather not have - it's your call though.

By the way, thanks for the dataset - I couldn't find any periodic table JSON web APIs anywhere!

**Comment by andrejewski** [comment]
If someone cannot handle the mental overhead of converting n to n-1, God have mercy on their soul. A method is worse than an object, in a sense that is all the method would be, just without `Object.keys()` and `Object.values()`. An array is much better because it has many methods along with plain bracket access. Note: if atomic numbers were not integer and bijective we would not be having this conversation, an object/method would be the best solution.

I will add my `sort()` snippet to the README to address this concern as I do not want anyone assuming an inherent order in the first place.

**Comment by nathanhleung** [comment]
I still think that the conversion from `n` to `n-1` is a relevant concern, though. [This issue](https://github.com/sindresorhus/ama/issues/10#issuecomment-117766328) regarding one-line modules gives some good points (essentially, one-line modules allow one to build more advanced things more easily). (see also: [is-negative-zero](https://www.npmjs.com/package/is-negative-zero))

In essence, I'd rather just have a method to get an element by atomic number than having to sort the array and then get the `n-1`th index, so then I can go and do bigger and better things! Food for thought. :smile:

Also, here's what I had in mind for the method (I wasn't planning on using `Object.keys()`):

```js
exports.byAtomicNumber = (n) => {
  return data.filter((el) => {
    if (el.atomicNumber === n) {
      return true;
    }
    return false;
  })[0];
};
```

While it's less efficient than a simple array, to me it's a lot easier. Let me know, and if you're set on not having a method that's fine, I can drop the issue.

**Comment by andrejewski** [comment]
I have read this one-liner post before and is-negative-zero is a solution to an obscure problem of JavaScript programming. Anyone who is programming should know `n-1` for arrays.

But I think you are right. Not for the mental overhead argument, but imagine a case in the future where we discover element 121 but not 120. The array would need a null value at the 119th index in order for indices-based access to work as expected. But then the sort function would need fixing. Removing the assumption that we will always find larger elements in order, an object does make the most sense.

So it seems we have come full circle:
```js
module.exports.numbers = data.reduce(function(obj, element) {
  obj[element.atomicNumber] = element;
  return obj;
}, {});
```

**Pull request closed without merging**
